import { z } from "zod";
import { PlatformSchema } from "./submission.schema";

/**
 * Weak Topic & Failure Mode identification from Person B's AI Agent
 */
export const WeakTopicSchema = z.object({
  topic: z.string().min(1, "Topic name is required (e.g., Binary Search, Dynamic Programming)"),
  failure_mode: z.string().min(1, "Specific recurring failure mode (e.g., Boundary condition errors, Incorrect state definition)"),
  confidence: z.number().min(0).max(1).describe("Confidence score between 0.0 and 1.0"),
  evidence_count: z.number().int().nonnegative().describe("Number of failing submissions exhibiting this pattern"),
  example_submissions: z.array(z.string()).describe("List of canonical submission_ids serving as evidence"),
  description: z.string().optional().describe("Optional deep-dive explanation generated by the agent"),
  root_cause: z.string().optional().describe("Primary algorithmic root cause"),
  why_it_fails: z.string().optional().describe("Explanation of why the logic breaks on test inputs"),
  correct_concept: z.string().optional().describe("Underlying algorithmic invariant or formula needed"),
  suggested_fix: z.string().optional().describe("Suggested fix or correct recurrence/pointer logic"),
});
export type WeakTopic = z.infer<typeof WeakTopicSchema>;

/**
 * Targeted Recommended Problem based on identified weaknesses
 */
export const RecommendedProblemSchema = z.object({
  platform: PlatformSchema,
  problem_id: z.string().min(1, "Problem identifier (e.g. 704 or 1850A)"),
  title: z.string().optional(),
  difficulty: z.string().optional(),
  topic: z.string().optional(),
  reason: z.string().min(1, "Targeted pedagogical reason why this problem will resolve the detected blind spot"),
  url: z.string().optional(),
});
export type RecommendedProblem = z.infer<typeof RecommendedProblemSchema>;

/**
 * Canonical AI Analysis Output Schema
 * Strict interface contract representing the analysis payload produced by Person B's Strands Agent
 * and consumed by Person A's OpenSearch, Scheduler, and Dashboard.
 */
export const AnalysisOutputSchema = z.object({
  user_id: z.string().optional().default("default_user"),
  analyzed_at: z.number().int().optional().default(() => Date.now()),
  summary: z.string().optional(),
  weak_topics: z.array(WeakTopicSchema),
  recommended_problems: z.array(RecommendedProblemSchema),
});

export type AnalysisOutput = z.infer<typeof AnalysisOutputSchema>;
