import { z } from "zod";

export const PlatformSchema = z.enum(["leetcode", "codeforces"]);
export type Platform = z.infer<typeof PlatformSchema>;

export const VerdictSchema = z.enum([
  "AC",
  "WA",
  "TLE",
  "MLE",
  "RE",
  "CE",
  "OTHER"
]);
export type Verdict = z.infer<typeof VerdictSchema>;

export const CanonicalProblemSchema = z.object({
  id: z.string().min(1, "Problem ID is required"),
  title: z.string().min(1, "Problem title is required"),
  difficulty: z.string().optional(),
  topic_tags: z.array(z.string()).default([]),
  url: z.string().url().optional(),
});
export type CanonicalProblem = z.infer<typeof CanonicalProblemSchema>;

export const CanonicalSubmissionDetailsSchema = z.object({
  language: z.string().min(1, "Language is required"),
  verdict: VerdictSchema,
  runtime_ms: z.number().nonnegative().optional(),
  memory_mb: z.number().nonnegative().optional(),
  timestamp: z.number().int(),
  code: z.string(),
  error_message: z.string().optional(),
});
export type CanonicalSubmissionDetails = z.infer<typeof CanonicalSubmissionDetailsSchema>;

/**
 * Execution Evidence extracted from runtime / test runner
 */
export const SubmissionEvidenceSchema = z.object({
  input: z.string().optional(),
  actual_output: z.string().optional(),
  expected_output: z.string().optional(),
  error_message: z.string().optional(),
});
export type SubmissionEvidence = z.infer<typeof SubmissionEvidenceSchema>;

/**
 * Algorithmic AI Diagnosis generated by Person B
 */
export const SubmissionAnalysisSchema = z.object({
  topic: z.string(),
  failure_mode: z.string(),
  failure_pattern: z.string().optional(),
  root_cause: z.string(),
  why_it_fails: z.string(),
  correct_concept: z.string(),
  suggested_fix: z.string(),
  code_location: z.string().optional(),
  confidence: z.number().min(0).max(1),
  is_failure: z.boolean().optional(),
  evidence: SubmissionEvidenceSchema.optional(),
  explanation: z.string().optional(),
});
export type SubmissionAnalysis = z.infer<typeof SubmissionAnalysisSchema>;

export const CanonicalSubmissionSchema = z.object({
  submission_id: z.string().min(1, "Submission ID is required"),
  user_id: z.string().optional().default("default_user"),
  platform: PlatformSchema,
  problem: CanonicalProblemSchema,
  submission: CanonicalSubmissionDetailsSchema,
  raw_payload: z.record(z.unknown()).optional(),
  analysis: SubmissionAnalysisSchema.optional(),
});

export type CanonicalSubmission = z.infer<typeof CanonicalSubmissionSchema>;
